# Generated by Django 2.2.7 on 2020-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunbo_url', models.CharField(default='', max_length=256, verbose_name='轮播地址')),
                ('img', models.CharField(default='', max_length=256, verbose_name='轮播图片')),
                ('lunbo_title', models.CharField(max_length=256, verbose_name='轮播标题')),
            ],
            options={
                'verbose_name': '轮播',
                'verbose_name_plural': '轮播',
            },
        ),
    ]
