# Generated by Django 2.2.7 on 2020-05-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='cloud_dict',
            field=models.CharField(blank=True, max_length=256, verbose_name='词云字典'),
        ),
    ]
