# Generated by Django 2.2.7 on 2019-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='prefer',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
