# Generated by Django 2.2.7 on 2020-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_info_cloud_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_base', models.CharField(max_length=64, verbose_name='ID_base')),
                ('user_id_sim', models.CharField(max_length=64, verbose_name='ID_sim')),
                ('user_correlation', models.FloatField(verbose_name='用户相关度')),
            ],
            options={
                'verbose_name_plural': '用户相似度表',
                'db_table': 'usersim',
            },
        ),
    ]
