# Generated by Django 2.2.7 on 2019-12-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191227_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='authorlink',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='articles',
            name='piclink',
            field=models.CharField(default='', max_length=256),
        ),
    ]
