# Generated by Django 2.2.7 on 2020-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200508_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefer',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
