# Generated by Django 2.2.7 on 2020-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191230_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baidu_Hotnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CSDN_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('profile', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('link', models.CharField(default='', max_length=256)),
                ('piclink', models.CharField(default='', max_length=256)),
                ('authorlink', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Jianshu_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('profile', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('link', models.CharField(default='', max_length=256)),
                ('piclink', models.CharField(default='', max_length=256)),
                ('authorlink', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.CharField(default=None, max_length=256)),
                ('channel', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sina_Hotnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sogo_Hotnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Weixin_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('profile', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('link', models.CharField(default='', max_length=256)),
                ('piclink', models.CharField(default='', max_length=256)),
                ('authorlink', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
