# Generated by Django 2.2.7 on 2020-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200509_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_cloud',
            name='cloud_time',
            field=models.DateTimeField(verbose_name='词云记录时间'),
        ),
    ]
