# Generated by Django 2.2.7 on 2020-01-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_baidu_hotnews_csdn_articles_jianshu_articles_settings_sina_hotnews_sogo_hotnews_weixin_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
    ]
