# Generated by Django 2.2.7 on 2020-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_settings_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_id', models.CharField(max_length=64, unique=True, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=64, verbose_name='名字')),
            ],
            options={
                'verbose_name_plural': '新闻类别表',
                'db_table': 'cate',
            },
        ),
        migrations.CreateModel(
            name='newbrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('new_id', models.CharField(max_length=64, verbose_name='ID')),
                ('new_browse_time', models.DateTimeField(verbose_name='浏览时间')),
            ],
            options={
                'verbose_name_plural': '用户点击表',
                'db_table': 'newbrowse',
            },
        ),
        migrations.CreateModel(
            name='newsim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id_base', models.CharField(max_length=64, verbose_name='ID_base')),
                ('new_id_sim', models.CharField(max_length=64, verbose_name='ID_sim')),
                ('new_correlation', models.FloatField(verbose_name='新闻相关度')),
            ],
            options={
                'verbose_name_plural': '新闻相似度表',
                'db_table': 'newsim',
            },
        ),
        migrations.CreateModel(
            name='newtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_tag', models.CharField(max_length=64, verbose_name='标签')),
                ('new_id', models.CharField(max_length=64, verbose_name='ID')),
                ('new_hot', models.FloatField(verbose_name='热度值')),
            ],
            options={
                'verbose_name_plural': '新闻标签表',
                'db_table': 'newtag',
            },
        ),
        migrations.CreateModel(
            name='newhot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(max_length=64, unique=True, verbose_name='ID')),
                ('new_hot', models.FloatField(verbose_name='热度值')),
                ('new_cate', models.ForeignKey(on_delete=False, related_name='类别名', to='login.cate')),
            ],
            options={
                'verbose_name_plural': '新闻热度表',
                'db_table': 'newhot',
            },
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(max_length=64, unique=True, verbose_name='ID')),
                ('new_time', models.DateTimeField(verbose_name='发表时间')),
                ('new_seenum', models.IntegerField(verbose_name='浏览次数')),
                ('new_disnum', models.IntegerField(verbose_name='跟帖次数')),
                ('new_title', models.CharField(max_length=100, verbose_name='标题')),
                ('new_content', models.TextField(verbose_name='新闻内容')),
                ('new_cate', models.ForeignKey(on_delete=False, related_name='类别', to='login.cate')),
            ],
            options={
                'verbose_name_plural': '新闻信息表',
                'db_table': 'new',
            },
        ),
    ]
