# Generated by Django 2.2.7 on 2020-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200510_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=64, unique=True, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=64, verbose_name='名字')),
                ('detail', models.CharField(blank=True, max_length=256, verbose_name='解答内容')),
            ],
            options={
                'verbose_name_plural': '帮助问题表',
                'db_table': 'answer',
            },
        ),
    ]
