# Generated by Django 2.2.7 on 2020-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=64, verbose_name='联系方式')),
                ('content', models.CharField(max_length=256, verbose_name='反馈内容')),
            ],
        ),
    ]
