# Generated by Django 2.2.7 on 2020-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_helpform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': '帮助问题表', 'verbose_name_plural': '帮助问题表'},
        ),
        migrations.AlterModelOptions(
            name='baidu_hotnews',
            options={'verbose_name': '百度热点', 'verbose_name_plural': '百度热点'},
        ),
        migrations.AlterModelOptions(
            name='cate',
            options={'verbose_name': '文章类别表', 'verbose_name_plural': '文章类别表'},
        ),
        migrations.AlterModelOptions(
            name='helpform',
            options={'verbose_name': '用户反馈表', 'verbose_name_plural': '用户反馈表'},
        ),
        migrations.AlterModelOptions(
            name='lunbo',
            options={'verbose_name': '轮播', 'verbose_name_plural': '轮播'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': '文章信息表', 'verbose_name_plural': '文章信息表'},
        ),
        migrations.AlterModelOptions(
            name='newhot',
            options={'verbose_name': '文章热度表', 'verbose_name_plural': '文章热度表'},
        ),
        migrations.AlterModelOptions(
            name='newsim',
            options={'verbose_name': '文章相似度表', 'verbose_name_plural': '文章相似度表'},
        ),
        migrations.AlterModelOptions(
            name='newtag',
            options={'verbose_name': '文章标签表', 'verbose_name_plural': '文章标签表'},
        ),
        migrations.AlterModelOptions(
            name='sina_hotnews',
            options={'verbose_name': '新浪热点', 'verbose_name_plural': '新浪热点'},
        ),
        migrations.AlterModelOptions(
            name='sogo_hotnews',
            options={'verbose_name': '搜狗热点', 'verbose_name_plural': '搜狗热点'},
        ),
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': '用户登录信息', 'verbose_name_plural': '用户登录信息'},
        ),
        migrations.AlterModelOptions(
            name='usersim',
            options={'verbose_name': '用户相似度表', 'verbose_name_plural': '用户相似度表'},
        ),
        migrations.AlterModelOptions(
            name='word_cloud',
            options={'verbose_name': '词云表', 'verbose_name_plural': '词云表'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='帮助问题ID'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_name',
            field=models.CharField(max_length=64, verbose_name='帮助标题'),
        ),
        migrations.AlterField(
            model_name='baidu_hotnews',
            name='link',
            field=models.CharField(default='', max_length=256, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='baidu_hotnews',
            name='title',
            field=models.CharField(max_length=256, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='cate',
            name='cate_name',
            field=models.CharField(max_length=64, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='img',
            field=models.CharField(default='', max_length=256, verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='lunbo_title',
            field=models.CharField(max_length=256, verbose_name='轮播标题'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='lunbo_url',
            field=models.CharField(default='', max_length=256, verbose_name='轮播地址'),
        ),
        migrations.AlterField(
            model_name='new',
            name='authorlink',
            field=models.CharField(default='', max_length=256, verbose_name='作者链接'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_content',
            field=models.TextField(verbose_name='文章简述'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='new',
            name='piclink',
            field=models.CharField(default='', max_length=256, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.CharField(default='', max_length=256, verbose_name='文章链接'),
        ),
        migrations.AlterField(
            model_name='newhot',
            name='new_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='newtag',
            name='new_id',
            field=models.CharField(max_length=64, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='sina_hotnews',
            name='link',
            field=models.CharField(default='', max_length=256, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='sina_hotnews',
            name='title',
            field=models.CharField(max_length=256, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='sogo_hotnews',
            name='link',
            field=models.CharField(default='', max_length=256, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='sogo_hotnews',
            name='title',
            field=models.CharField(max_length=256, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=256, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='brief',
            field=models.CharField(blank=True, max_length=256, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='喜好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=256, verbose_name='公司/学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=256, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefer',
            field=models.CharField(blank=True, default='', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('none', '保密')], default='保密', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='truename',
            field=models.CharField(blank=True, max_length=256, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='usersim',
            name='user_id_base',
            field=models.CharField(max_length=64, verbose_name='User_base'),
        ),
        migrations.AlterField(
            model_name='usersim',
            name='user_id_sim',
            field=models.CharField(max_length=64, verbose_name='User_sim'),
        ),
    ]
